### ISSUE TITLE
Context weights

### ISSUE THREAD

**Issue by thallingstad** [goml/gobrain#10]
Should not the contexts have a separate set of weights?

```go
	for i := 0; i < nn.NHiddens-1; i++ {
		var sum float64

		for j := 0; j < nn.NInputs; j++ {
			sum += nn.InputActivations[j] * nn.InputWeights[j][i]
		}

		// compute contexts sum
		for k := 0; k < len(nn.Contexts); k++ {
			for j := 0; j < nn.NHiddens-1; j++ {
				sum += nn.Contexts[k][j]
			}
		}

		nn.HiddenActivations[i] = sigmoid(sum)
	}
```

Without `ContextWeights`, the contexts sum is equal for every hidden node and there's no reason to recalculate it for each one. Am I missing something?

**Comment by jonhkr** [comment]
Hi @ebbot654 

As far as I understood, the connections from the hidden layer and the context should always have weight `1.0` (http://mnemstudio.org/neural-networks-elman.htm), that's why we don't have a set of weights for the contexts.

Let me know if that makes sense.

**Comment by ebbot654** [comment]
Hello @jonhkr

"Recurrent connections are fixed at 1.0 and are not subject to adjustment."

This is my understanding: The recurrent connections, which stores the hidden layer output into a context layer, are fixed. But the forward connections from the context layers to the hidden layer (illustrated in the article) act as in a regular Feed Forward NN and are weighted. It does not make sense to add the same sum to every hidden node activation, as is the result without weights.

**Comment by jonhkr** [comment]
Ah, now I get it, would you mind rebasing your PR, tests were failing in the master branch by the time you opened it.

**Comment by thallingstad** [comment]
Done :)
